/*
Each new term in the Fibonacci sequence is generated by adding the previous two
terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
*/
package main

import "fmt"

func main() {
  val1 := 1
  val2 := 2
  sum := 2
  newVal := 0
  for newVal < 4000000 {
    newVal = val1 + val2
    if newVal%2 == 0 {
      sum += newVal
    }
    val1 = val2
    val2 = newVal
  }

  fmt.Println(sum)
}

// result = 4613732
